sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/agent.py

When the ap-name was too long, it was overlapping with the "AUTO" text... I suggest to limit the ap-name to 20 chars (should be enough).

Fix overlapping issue

---

scripts/create_sibling.sh

Had to add resolv.conf to get DNS resolution when working on this last night. Within chroot, apt / pip wouldn't update, fixed by adding this

adding resolv.conf for DNS resolution in chroot

---

sdcard/rootfs/root/pwnagotchi/config.yml
sdcard/rootfs/root/pwnagotchi/scripts/main.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/log.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/ui/display.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/ui/fonts.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/ui/view.py
sdcard/rootfs/root/pwnagotchi/scripts/requirements.txt

This PR adds the following changes:
- Support for InkyPHAT displays
- Configuration options to configure said displays under the 'ui' branch of the config.yml file
- Adds initial support for dynamic elements positioning on the screen (untested in other screens, also the element of 2 pwnagotchis communicating was not adjusted as I'm waiting for my second pi to test it)
- The face font size was changed to allow it to fit on smaller screens, functionality to dynamically change yet to come
- Minor change to move the temporary twitter image to /dev/shm to avoid unnecessary SD card writes

Support for InkyPHAT displays from pimoroni using the inky library

---

sdcard/rootfs/etc/network/interfaces

We've been getting quite a few raspberry pi users that are not using rpi0w, which makes really hard to use the ethernet gadget mode as it would require a usb-a to usb-a cable, which is not common.
To make the experience easier, I'm adding eth0 with dhcp configuration, this way an ethernet cable can be connected and access can be done using MDNs

Enable  eth0 if it exists for users using other pi that are not the pi0w

---

scripts/create_sibling.sh
scripts/linux_connection_share.sh
sdcard/boot/config.txt
sdcard/rootfs/etc/rc.local
sdcard/rootfs/root/pwnagotchi/data/screenrc.auto
sdcard/rootfs/root/pwnagotchi/data/screenrc.manual
sdcard/rootfs/root/pwnagotchi/scripts/blink.sh

This PR disable services that are not necessary at the moment, if they are in the future we can re-enable them.
This will allow us to speed up the boot process, save memory and also battery usage from users running portable.
Services disabled:
- triggerhappy
- bluetooth
Powersave changes:
- Disable power LED (According to some blog posts it saves ~30ma)
- Disable bluetooth
- Disable audio
- Disable HDMI (Also saves ~30ma)
Also some minor shellcheck fixes.
If we start using bluetooth in the future, we need to change config.txt and re-enable the bluetooth service.

services cleanup. powersave features and shellcheck fixes

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/ai/train.py

My pwnagotchi crashed, because the brain.json was somehow empty.

Empty brain leads to crash

---

scripts/create_sibling.sh
scripts/linux_connection_share.sh
sdcard/rootfs/root/pwnagotchi/scripts/blink.sh
sdcard/rootfs/root/pwnagotchi/scripts/startup.sh

The scripts (particularly referring to the ones in the [scripts](https://github.com/evilsocket/pwnagotchi/tree/master/scripts) folder) seem to assume that there's a bash executable under the path `/bin/bash`, so I went ahead and changed all instances of shebangs from `#!/bin/bash` to `#!/usr/bin/env bash`.
I'll admit that this is a very minor change, but I believe that the upside of that said change (portability) would be a cool detail! :)

Changed hardcoded paths

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/ui/display.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/ui/papirus/epd.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/ui/papirus/lm75b.py
sdcard/rootfs/root/pwnagotchi/scripts/requirements.txt

**What?**
This includes the PaPiRus driver files in the project, in a similar way to which the Waveshare drivers have been included. This means that users will not need to follow the installation process for these drivers after provisioning a sibling.

Include PaPiRus drivers in project

---

README.md
scripts/language.sh
scripts/preview.py

I tried to implement a small preview for the pwnagotchi display (currently waveshare v2 specs).
So while creating a new translation, you can open the preview with:
`./scripts/languange.sh test`
It should look like this:
You get a rough estimation of the text width and invalid characters are displayed as "blocks".
You need a internet connection, because it will download 2 Fonts.
1. DejaVu Sans
2. LastResort (this will catch all the invalid characters which can't be displayed)
It's just an idea i had and needs some testing...

Add pwnagotchi preview

---

scripts/create_sibling.sh

Add -A option so that one can pass in the URL of a APT Proxy (eg apt-cacher-ng) so that rebuilding is much faster

APT Proxy support

---

scripts/create_sibling.sh

Without this I'm getting a constant segmentation fault when running go under qemu on Fedora 30:
+ export GOPATH=/root/go
+ GOPATH=/root/go
+ go get -u github.com/bettercap/bettercap
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
bin/bash: line 52: 23146 Segmentation fault      (core dumped) go get -u github.com/bettercap/bettercap
https://bugs.launchpad.net/qemu/+bug/1696773

Fix for the segmentation fault in qemu

---

.gitignore
.travis.yml
scripts/create_sibling.sh

This uses https://github.com/intel/bmap-tools to generate a .bmap file
which can be copied around. The bmaptool allows storing sparse files
onto for instance an SD card, thus avoiding having to transfer the full
disk image every time one burns one.
Thus saving lots of time (and SD card cycles).
This also adds some instructions for then transfering and copying the
sparse file.
bmaptool: info: discovered bmap file '/Users/jeroen/berry.img.bmap'
bmaptool: info: block map format version 2.0
bmaptool: info: 7324219 blocks of size 4096 (27.9 GiB), mapped 1539940 blocks (5.9 GiB or 21.0%)
bmaptool: info: copying image 'berry.img' to file 'rdisk4' using bmap file 'berry.img.bmap'
bmaptool: info: 100% copied
bmaptool: info: synchronizing '/dev/rdisk4'
bmaptool: info: copying time: 6m 49.7s, …

Enable detection of bmaptool, and if present generate sparse files.

---

.travis.yml
scripts/create_sibling.sh

hey,
currently it's not possible to build an image without setting the image size manually to 8gb. There is already a workaround in travis.yml which imho should be moved to the create_sibling.sh script.

Default to 8GB Images

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/log.py

Fixes bug where on initial session there is no file, and thus no lines
are read and one thus gets a index out of bounds error as lines is empty...

Fix initial non-existent/empty log issue

---

README.md

The display seems to need a complete power off in some cases to work.

Describe issue with rebooting after changing the display

---

.travis.yml

As we are not using branches to tag, we don't need travis to add tags.
This is being removed because it breaks the build.

remove tagging from travis

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/memtemp.py

shows available, used and free memory + CPU temperature in celsius on ui on defined refresh rate (default 30 seconds)
plugin for add available, used and free memory + CPU temperature in celsius on ui on defined refresh rate (default 30 seconds)
the plugin is default disabled
tested on raspbery0w with MASTER code
plugin file added

add default plugin for showing memory infos and cpu temperature

---

builder/pwnagotchi.yml

The memusage script created by our ansible build is missing bash on the shebang
This PR fix this issue

fix broken memusage script

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/ui/view.py

It takes its queue from the bottom line and places text above it.
Tested on WaveShare v2 and Inkyphat.
Potential further improvement is getting the font height, and using that as the basis for the positioning, including a buffer.

Friend status is positioned based on %age of screen height

---

scripts/create_sibling.sh
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/ui/display.py

I noticed while doing some TFT / SPI work that the renders can crash the main thread locking up the program with
```
[2019-10-04 00:44:15,060] [INFO] started advertiser thread (period:0.3 sid:ae:76:42:79:14:93) ...
Unhandled exception in thread started by <bound method Agent._event_poller of <pwnagotchi.agent.Agent object at 0x757ad2d0>>
Traceback (most recent call last):
File "/root/pwnagotchi/scripts/pwnagotchi/agent.py", line 337, in _event_poller
self._update_peers()
File "/root/pwnagotchi/scripts/pwnagotchi/agent.py", line 290, in _update_peers
self._view.set_closest_peer(peer)
File "/root/pwnagotchi/scripts/pwnagotchi/ui/view.py", line 211, in set_closest_peer
self.update()
File "/root/pwnagotchi/scripts/pwnagotchi/ui/view.py", line 330, in update
cb(self._canvas)
File …
```

Fixed Render crashing main thread

---

README.md
scripts/create_sibling.sh

Removed bmap-tools from depends as the check on line 96 looks for bmaptools and would use it if available if not continue to build, but have it as a depend check made the check null and if someone is on a kernel/file-system that does not support SEEK_HOLE and SEEK_DATA the script stops and asks to install bmap-tools and causes an error during creation when using bmap-tools if the system does not support SEEK_HOLE and SEEK_DATA
Updated bmap-tools check as the line which bmaptool >/dev/null 2>&1 did not return 0 so it kept ending at this line, with bmap-tools not installed
The original code below looks for sparse to be 0 and if which bmaptool >/dev/null 2>&1 returns 0 to use bmap-tools, but I think its the reverse so swapped the last then and else sections as it would then look if sparse is …

Updated depends, updated bmap check

---

sdcard/rootfs/root/pwnagotchi/config.yml
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/__init__.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/example.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/onlinehashcrack.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/twitter.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/wpa-sec.py

See #129 
Now you can configure the plugins via `config.yml`.
Each plugin has an `OPTIONS`-dict with the values in it.
You can use it like:
```yaml
main:
plugins:
example:
enabled: True
api_key: '1234567'
```
```python
if OPTIONS['enabled']:
print('I am enabled and using the api-key ' + OPTIONS['api_key'])
```

Configure plugins via config.yml

---

scripts/update_pwnagotchi.sh

The update script backs up the config file to `/root/config.bak`, but
then tries to restore it from `/root/config.yml.bak` (which obviously
won't be found).
This looks like a typo in the backup command, so update that command to
use the same filename as the restore command.
Ran the updated script on my pwnagotchi and confirmed that the files were backed up and restored as expected.

Fix incorrect config filename in update script

---

sdcard/rootfs/root/pwnagotchi/config.yml
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/auto-backup.py

Changed method to Popen. Also changed yaml -> yml. And now the plugin is more verbose.

Fix split-bug in script

---

builder/pwnagotchi.yml

Added two more sections in the Ansible file to generate the hdmion and hdmioff scripts in order to be able to (easier) turn on and off the HDMI functionality.
I wanted to be able to turn off HDMI when I go between power and battery usage. Every little bit to save battery is worth it...
Have verified that the scripts work. Tried to build a new image but since the re-arch and loss of the sdcard folder the create_sibling.sh script currently fails. (I think issue https://github.com/evilsocket/pwnagotchi/issues/170 references this too).
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My change requires a change to the documentation.
- [x ] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/ma …

Added hdmion/hdmioff scripts

---

pwnagotchi/locale/el/LC_MESSAGES/voice.po

I fixed two small spacing-related mistakes in the Greek translation of Pwnagotchi.
I added two spaces. That's about it, really.
It just didn't seem quite visually pleasing.
It hasn't been tested, because of the triviality of the fix itself.

fixed spacing error in greek translation

---

scripts/create_sibling.sh

When doing some testing I was able to determine the second check for bmaptool would return a false 1 and cause at the end of the create script to think bmap-tools is installed. I did some research and testing and updated it to use a different check. Also removed and extra carriage return. To test i added a couple of echo's to the if and else section to print what OPT_SPARSE was and then had it stop so I did not have to let it fully finish each time i tested it. Each time it printed OPT_SPARSE was 0 and showed the right echo line.

Updated bmaptool check #2

---

setup.py

Bug fix for installation of pwnagotchi using setup.py
This change fixes a bug with the new setup.py script if used to install the pwnagotchi software. Once installed, running '/usr/local/bin/pwnagotchi' returns the following error:                                                                                                                                                                                               Traceback (most recent call last):
File "/usr/local/bin/pwnagotchi", line 8, in <module>
import pwnagotchi
ModuleNotFoundError: No module named 'pwnagotchi'
Tested using with the "pwnagotchi -C /root/defaults.yml --manual"

Fixes "No module named 'pwnagotchi'" error

---

pwnagotchi/plugins/default/wpa-sec.py

If you use the gps-plugin, the `.gps.json` files are also written in the handshake directory. The plugin assumed, that every file in the directory would be a pcap.

Fix bug with gps.json files

---

builder/pwnagotchi.yml

The loader will check if the file /root/.pwnagotchi-auto exists, if it exists it will be removed and pwnagotchi will be started in auto mode.

add override file check to loader

---

.travis.yml
Makefile
builder/pwnagotchi.json
builder/pwnagotchi.yml

Our builder was not respecting the hostname and version tag set on travis.
This PR fixes it.
Sadly packer is not passing variables to ansible via --extra-vars, so it was required to fill the environment first with environment variables.
I test this locally and seems to be working as expected, it adds the hostname configured to the machine and also sets the version on /etc/motd

fix builder to set image version and hostname on build

---

builder/pwnagotchi.yml

This PR is related to #234 
- It downloads Pairus dependencies and installs it
- It enabled the I2C bus to allow papirus drivers to talk to it
- It enables the service required to run (epd-fuse)
This change was motivated by the issue raised which was related to the lack of support for papirus displays on the operational system level.
I don't have a papirus to test but I could verify that all it's dependencies installed correctly based in what was reported on the issue.

add papirus display system requirements

---

bin/pwnagotchi
pwnagotchi/ui/display.py
pwnagotchi/ui/view.py

Changed the View so the Display is injected into it, rather than subclassing.
This allows the View to reference the display for appropriate settings and use it for the rendering without knowing anything about the epaper type.
The epaper classes (eg WaveShare2Display, InkyPhatDisplay) hold the display-specific information (rendering, display specifics, initialisation, config display type)
The display class manages these, finds the appropriate class for the config. 
The View class calls out to the display which then calls out to the ePaper class.
Http Rendering is still done as part of the display - could possibly be separated and become its own display in a later refactor.
If a new ePaper type comes along, create a new class that adheres to the public methods, and add the class to the …

SOLID principles on Display/View classes

---

Makefile
builder/pwnagotchi.yml

Cleanup to put some standards, half of the files used blockinfile, the other half used copy.
Now they  are using copy, which does not put the `MANAGED BY ANSIBLE` placeholder leaving a cleaner look.
Also before creating config.yml, ansible checks if it already exists, this way ansible can be used for update or to reset to almost factory settings the unit by using `PWN_HOSTNAME=$(cat /etc/hostname) PWN_VERSION=custom ansible-playbook /usr/local/src/pwnagotchi/builder/pwnagotchi.yml`

Add hold for firmware and minor cleanup

---

pwnagotchi/mesh/advertise.py

- Scapy 2.4.3+ (pinned by `pwnagotchi`) has fixed https://github.com/secdev/scapy/issues/1590.
The workaround isn't necessary anymore, and because we haven't documented it anywhere, I find it confusing.
I would like other projects not to copy this workaround.
I fixed the Scapy issue in February. We haven't had any more reports since

Remove Dot11FCS workaround

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/bt-tether.py

This plugin teaches pwnagotchi how to communicate over bluetooth.
Added the bt-tether.py file which contains code to establish a bluetooth-connection.
Related configs are these:
```yaml
main:
plugins:
bt-tether:
enabled: false # if you want to use this, set ui.display.video.address to 0.0.0.0
mac: ~ # mac of your bluetooth device
ip: '192.168.44.44' # ip from which your pwnagotchi should be reachable
netmask: 24
interval: 1 # check every minute for device
```
- [ x ] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))
See #274 
Tested by me, daPwni (slack; but older version)
- [ x] New feature (non-breaking change which adds functionality)
- [x ] My change …

Add bluetooth plugin

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/bt-tether.py
pwnagotchi/plugins/default/memtemp.py
pwnagotchi/ui/hw/inky.py

On inky displays, the last total recon APs status sometimes overlaps with the channel status depending on the channel it is on.
The BT status overlaps with the last total recon status. This might be an issue only on inky displays, but since this is controlled by the bt-tether plugin it will apply to all screens.
Making the UI not showing garbage on the display. This makes all statuses show correctly and readable.
https://github.com/evilsocket/pwnagotchi/issues/315
After the changes the UI looks clean and no more overlap.

Minor fixes to the UI to prevent overlap 

---

pwnagotchi/ui/hw/libs/papirus/epd.py

Fixed LM75B import error
Appended the missing lm75b to the import string in epd.py
Without the change, the pwnagotchi service fails when using a papirus screen.
- [x ] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))
The pwnagotchi (with a papirus screen) correctly boots after the modification
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide

Fix LM75B import error for Papirus Screens

---

pwnagotchi/plugins/default/grid.py

Changed UI logic in the Grid plugin to only display details if you have unread messages instead of any messages at all
There's no reason for a visual indicator if you've read all of your messages, and it's a little satisfying to clear the "notification" once the inbox is all dealt with.
It just works™

Only show ui complication if you have unread pwnmail

---

requirements.txt

See #324 
We need to use an old version of the gast-requirement. I tested this and it worked!

need old gast version

---

requirements.txt

See #258 
Tested with the newest version (v1.0.1)
python3 -c "import tweepy" crashes

increase version

---

pwnagotchi/ui/web.py

```python
Handler.AllowedOrigin = 'https://safe.com'
origin = 'https://safe.com.evil.com'
origin.startswith(Handler.AllowedOrigin) == True
```
Not really bypass, since it has typo `starts_with` -> `startswith`, but if you fixed typo..

Fix Origin header check bypass

---

pwnagotchi/defaults.yml

Part 1 of closing https://github.com/evilsocket/pwnagotchi/issues/347, doing this from a device with only browser access to GH so will be done across 2 PR's.

Make wpa-sec URL configurable, part 1.

---

pwnagotchi/ui/hw/waveshare27inch.py

Signed-off-by: Mike van der Vrugt <mimij68@live.nl>
I have made the overall look of the layout for the 2.7" e-Paper display much better. Now it fully uses the whole screen while it still looks good (and cute).
Some images: https://imgur.com/a/8A60RVf

Changed the overall look of the layout on the 2.7"

---

builder/pwnagotchi.yml

- Fixes the i2c and spi configuration to allow papirus screens to work as expected.
- It changed boot.txt with the proper configuration
- Adds management to /etc/modules to add the i2c module
- Adds the package `fbi` to enable the frame buffer display functionality
- Adds idempontency check to ansible tasks (to help with development units)
- avoids reinstalling packages already installed like tensorflow and opencv. It checks package existency and also version installed
- avoids rebuilding packages already installed, if the git clone has no changes, it will not rebuild (papirus repos).
- does not change the hostname, unless it's the default `raspberrypi` hostname
- fixes /etc/hosts
- It changes the entry for 127.0.1.1 instead of 127.0.0.1 to be compatible with `raspi-config`
@dadav could …

papirus, fbi and idempotency changes

---

pwnagotchi/plugins/default/wigle.py

> csv.QUOTE_NONE
Instructs writer objects to never quote fields. When the current delimiter occurs in output data it is preceded by the current escapechar character. If escapechar is not set, the writer will raise Error if any characters that require escaping are encountered.
So, if there is a comma in the ESSID, an error was raised..

[Fix] Wigle plugin - add escape char

---

pwnagotchi/plugins/default/auto-backup.py

Currently it's not clear if the auto-backup fails without looking into the logs.
This change shows a warning on screen if the auto-backup failed (for whatever reason)
Testes on my PiZ in context of #391

Show information on failed backup on display

---

pwnagotchi/defaults.yml
pwnagotchi/utils.py

update docs to include missing lcdhat reference and enable lcdhat in utils.py (you can configure it but it's not accepted)

Add missing lcdhat

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/paw-gps.py

I added the plugin paw-gps and added one option to the config file
The plugin saves every time a handshake is captured, the gps position from the smartphone over the paw server
I tested the plugin myself on a RPI Zero W with the Paw server running on my Sony Xperia with the bt-tether plugin
New feature (non-breaking change which adds functionality)

Added plugin PAW GPS

---

pwnagotchi/defaults.yml
pwnagotchi/ui/display.py
pwnagotchi/ui/hw/__init__.py
pwnagotchi/ui/hw/dfrobot.py
pwnagotchi/ui/hw/libs/dfrobot/LICENSE
pwnagotchi/ui/hw/libs/dfrobot/dfrobot.py
pwnagotchi/ui/hw/libs/dfrobot/dfrobot_epaper.py
pwnagotchi/ui/hw/libs/dfrobot/gpio.py
pwnagotchi/ui/hw/libs/dfrobot/spi.py
pwnagotchi/utils.py

I've added support for the DFRobot 2.13in eink display.
This addition includes a slimmed down version of the DFRobot provided libraries. 
The DFRobot display is a bit more easy to find in stock than the waveshare monochrome displays at the moment (this project is probably making waveshare both a lot of money, and confused at the same time). I had a couple of them available, and decided to add support.
The panel is very close to the waveshare v1 display, but I was unable to get the waveshare driver to work with it, so I added support using DFRobot's driver library.
Tested on a rpi0w with two separate display modules.
Should not affect any existing code, as any changes to the main code has been added with elif statements.
Picture of display here: …

Add support for DFRobot epaper display

---

builder/pwnagotchi.yml

Don't disable video output if a DVI display is attached.
Currently when a DVI display is attached video output is still getting disabled.

Don't disable display output for DVI as well. fixes #429

---

pwnagotchi/plugins/default/AircrackOnly.py

Fixes #398.
AircrackOnly plugin wasn't working because of a typo: marking files for deletion referenced a wrong variable.
On a related note, it might be a good idea to make this plugin part of the core functionality, as it would reduce the clutter. On the other hand, it'll introduce the `aircrack-ng` dependency. What do you think?

Fix the AircrackOnly plugin

---

pwnagotchi/ui/web.py

Missed giving the argument to actually be able to write the response.
Just added 'self' as argument
Fixes #421 
I called the example plugin webhook

Fix for #421 / Webhook missing positional argiment

---

pwnagotchi/ui/display.py
pwnagotchi/ui/hw/__init__.py
pwnagotchi/ui/hw/libs/waveshare/v154inch/epd1in54b.py
pwnagotchi/ui/hw/libs/waveshare/v154inch/epdconfig.py
pwnagotchi/ui/hw/waveshare154inch.py
pwnagotchi/utils.py

The changes add support for the Waveshare 1.54 screen B version (the only one I'm able to test). Adding support for other versions should not be hard, only add python driver files in `libs` dir.
- Add official waveshare python driver in the `libs` folder
- Add `Waveshare154inch` class to interface driver, map ui elements to new screen ration (1:1)
- Update support for waveshare 1.54 inch screen in user config file
I had a 1.54 inch e-ink screen at home I wanted to use for the project
It has been testes on real hardware.
What has not been tested is the position of the friend face even though it should be no problem.

Add support for Waveshare 1.54 inch screen

---

pwnagotchi/ui/hw/inky.py

Made a specific color option called 'fastAndFurious' based on similar work in https://github.com/evilsocket/pwnagotchi/pull/428 - this is an emphatic opt-in to use the fast refresh that avoids the black flash, and updates the timings.
InkyPHATFast is a subclass of InkyPHAT so all functionality is matched. When the inky is initialising, if the color 'fastAndFurious' is selected, the InkyPHATFast library is used.  A warning is generated via logging Info.
If any other color is used, the standard Inky library is imported.
When rendering, if Black or 'fastAndFurious' are detected the default is 2 colors, otherwise it is 3 colors.
Resolves several requests to have the original Inky rendering as an option. Discussion in Slack regarding an instance of burn-in prompted an enhancement request …

InkyPHAT opt-in for fast refresh

---

pwnagotchi/defaults.yml

Adding info about display's config option to the comment in `defaults.yml`
- For the sake of completeness the comment with the existing screens should be maintained to reflect the supported screens. 
No test needed, there is only a change inside of a comment.

Waveshare 1.54 inch screen - config possibility in defaults.yml

---

scripts/backup.sh

Signed-off-by: Ciara Brennan <ciara.brennan@gmail.com>
Added a check to see if zip is installed before proceeding, and exit if user needs to install zip
Needed to add this as apparently zip doesn't come as default in my  Ubuntu WSL. 
https://github.com/evilsocket/pwnagotchi/issues/455
(https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))
Tested in Ubuntu WSL by running ./backup.sh before and after the change, installed zip, re-run script and confirmed backup.sh script outputs the expected zip file

check zip is installed first before running backup

---

pwnagotchi/ui/hw/lcdhat.py

There is a typo (uppercase / lowercase) which prevents the lcdhat display from initializing.
It was introduced with this change: https://github.com/evilsocket/pwnagotchi/commit/277906a6738553263db0174d003dd1367137423e
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide

Fix lcdhat _display.clear()

---

builder/pwnagotchi.yml

Issue #460 - Originally noted by @ZeroCool-Dade
https://github.com/evilsocket/pwnagotchi/commit/a78a4b0b3e5cfbdfea481e140e6c02e0bdb1f72d#commitcomment-35683998
Signed-off-by: Lorenzo Milesi <io@maxxer.it>
Fix eth0 check, as it's currently detected as always up thus starting pwnagotchi in MANU mode on Raspberries with eth0 port
I've tried starting and restarting pwnagotchi with the fix applied and no ethernet cable connected it starts in AUTO. With cable connected it will start in MANU.

Fix eth0 connection check for MANU mode

---

pwnagotchi/utils.py
scripts/preview.py

Wrapped the config.yml loading with a try/except and reports back smaller exception details than  traceback.
The section marked 'load a user config' now has an exception handler specifically for the YAMLError exception. Other issues will generate a full traceback but the exception handling could be expanded in future.
Typical output on an invalid config.yml:
```
There was an error processing the configuration file:
while parsing a block mapping
in "/etc/pwnagotchi/config.yml", line 18, column 7
expected <block end>, but found '<scalar>'
in "/etc/pwnagotchi/config.yml", line 22, column 18 
```
A valid configuration file allows program to run without exception being raised.
There were several issues raised in Slack where new users did not know they were getting configuration errors. This is …

Added exception handling to config.yml parsing

---

builder/pwnagotchi.yml

As most users won't use a big GUI, it should be sufficient to have 16MB assigned to the GPU and have some more for the system.
By default 64MB RAM are assigned to the GPU, this can be changed in `config.txt` to 16MB
You get more available RAM which is always nice ...
set the value on my pi

Change memory splitting to have more memory available

---

pwnagotchi/plugins/default/grid.py

Signed-off-by: Jeremy O'Brien <neutral@fastmail.com>
Currently the grid plugin will blindly attempt to parse the filenames of any pcaps found in /root/handshakes. If the pcap doesn't match our specific expected filename format, we should probably skip said pcap. This change does just that.
Added a check to ensure that the parsed MAC of a given pcap filename actually looks like a MAC before we hit the public grid API.
Gets rid of the following exception when a randomly named pcap ends up in /root/handshakes:
```
[2019-10-30 19:26:16,210] [INFO] grid: 1 new networks to report
[2019-10-30 19:26:16,292] [INFO] grid: parsing /root/handshakes/aiesrnt.pcap ...
[2019-10-30 19:26:16,689] [ERROR] grid: Not a supported capture file
[2019-10-30 19:26:17,190] [ERROR] error while reporting ap …
```

fix: don't attempt to parse/upload pcaps with malformed filenames

---

scripts/backup.sh
scripts/restore.sh

- Significantly decrease time it takes to save a backup
- Remove host dependency on 'zip' binary
- Preserve file attributes on backed-up files
- Avoid copying files on the pi itself to /tmp
Signed-off-by: Jeremy O'Brien <neutral@fastmail.com>
The backup script takes a long time to complete and puts a non-trivial amount of overhead on the pi during this time. By doing a minimum amount of work on the pi (creating an uncompressed tar of the relevant files to back up, sent through a pipe), the pi can get its portion of the backup task done very quickly. If the only purpose of taking a backup is to then later restore said backup, it shouldn't matter what format we keep the backup in, as long as we provide a way to restore the backup (which is included in the new `restore.sh` file).
The …

enhancement: Improve the backup script

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/bt-tether.py

Well, now you can connect multiple devices at the same time.
Legacy configuration is still supported, so updating should not be a problem.
New config looks like this:
```
bt-tether:
enabled: false # if you want to use this, set ui.display.video.address to 0.0.0.0
devices:
android-phone:
search_order: 1 # search for this first
mac: ~ # mac of your bluetooth device
ip: '192.168.44.44' # ip from which your pwnagotchi should be reachable
netmask: 24
interval: 1 # check every minute for device
scantime: 10 # search for 10 seconds
max_tries: 10 # after 10 tries of "not found"; don't try anymore
share_internet: false
priority: 1 # low routing priority; ios (prio: 999) would win here
ios-phone:
search_order: 2 # search for this second
mac: ~ # mac of your bluetooth device
ip: '172.20.10.2' # ip …
```

Add multi bt-tether support

---

pwnagotchi/plugins/default/AircrackOnly.py

The code will always delete the pcap file regardless of if there is a PMKID or Handshake due to the structure of the if statements. Added a new variable handshakeFound that will allow the file not to be deleted if there is a handshake and also it will scan for PMKID only if no handshake is found... If no handshake is found and no PMKID, only then the file is marked as to be deleted
- [ x ] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))
https://github.com/evilsocket/pwnagotchi/issues/506
Not tested it yet 
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code follows the code style of this project.
- [ x ] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CO …

Bug Fix on AircrackOnly.py plugin

---

pwnagotchi/__init__.py
pwnagotchi/ui/web.py

As requested in issue #502 I've added in the web UI a button that reboots the pwnagotchi into AUTO mode.
https://github.com/evilsocket/pwnagotchi/issues/502
Tested on my pwnagotchi and everything seems to run just fine.

Added "Reboot into AUTO mode" button in web ui

---

pwnagotchi/ui/web.py

Signed-off-by: Jeremy O'Brien <neutral@fastmail.com>
shotgunned the various style properties for inducing pixelated images in most "mainstream" browsers.
Make pwnagotchi face not blurry
Verified pixelated image shows in Firefox 70 and Chrome 78

fix: use a css class for the pixelated property, since apparently this still isn't standardized among different browsers

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/auto-backup.py

Added a "max_tries" parameter to the auto-backup plugin. If e.g. sshd isn't running on your backup host, the plugin would try it again and again. With this parameter you can prevent that.

Add max_tries param

---

pwnagotchi/plugins/default/AircrackOnly.py

Unnecessary/Wrong call to the super init method prevents AircrackOnly to load during startup
Removed call to super(),__init__ method.
Resolve issue 
- [ x ] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))
https://github.com/evilsocket/pwnagotchi/issues/536
Removed the call to super init method from local Pwnagotchi and restarted. AircrackOnly plugin now loads correctly
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code follows the code style of this project.
- [ x ] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide

Bug Fix on AircrackOnly Plugin preventing it to load

---

pwnagotchi/plugins/default/net-pos.py

I currently have some broken net-pos files on my device and the logging does not provide enough information to find the invalid files. I'd suggest to log the path.
Currently the net-pos plugin only logs out the Error message but not which error happened and on which file. 
manually

Additional Logging for net-pos plugin

---

pwnagotchi/ui/web/static/css/style.css
pwnagotchi/ui/web/static/js/viewportHeight.js
pwnagotchi/ui/web/templates/index.html

So, let's try again for #535 ... 
I added some styling to the webui which should prevent the image from overflowing and hiding the buttons. 
As for now I opted to always show the buttons below the image and use the remaining space above for the image. If the image does not fit in this space, it is resized keeping the aspect ratio. 
Sadly this requires some javascript to calculate the actual browser height (100vh does not work on mobile) but hey... I did not add any recalculation, so the image does not work in all cases when the browser is resized (or the device is rotated) but a reload fixes this. Should be fine imho.
I also think, that it'd be fair to say, that the target group for the webui are modern browsers, so I used flexbox which does not work 100% on IE11 but on all "normal" …

#523: Add some styling to webui

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/webcfg.py

**Idea**
With this plugin you can change the configuration via. browser on your computer or while walking around with a established bluetooth connection.
**Usage**
You have to enable the plugin in your config (**enabled: true**). After that you can simply open the browser and navigate to **http://\<pwnagotchi ip\>:\<port\>/plugins/webcfg**
You can use the top menu to add new options. If you want to add another item to an array, do it like `bettercap.silence.#12`. This would add the 13th item to the list (remember: arrays start from 0).
With the dropdown on the left of the add button you have to select the option-data-type. You can choose between **text** and **number**.
When you press **save**, the config will be saved to **/etc/pwnagotchi/config.yml**. Then the pwnagotchi will restart …

Add webcfg

---

pwnagotchi/plugins/default/memtemp.py

adding various temperature scales
Added Fahrenheit and Kelvin temperature conversion.
I wanted Fahrenheit and figured why not add Kelvin too.
https://github.com/evilsocket/pwnagotchi/issues/563
I tested on my rpi0w hw v 1.1, pwnagotchi v1.2.1. set scale to 'celsius', 'fahrenheit', and 'kelvin' in config like:
memtemp:
enabled: true
scale: 'fahrenheit'

Add Fahrenheit and Kelvin temperature scales to memtemp.py

---

pwnagotchi/plugins/default/gpio_buttons.py

i had with the old value 250 many double executions, despite short push switches. The new value 600 prevents this.
Tested with volume buttons on v1.2.1.

prevent double execution on gpio buttons

---

.gitignore
scripts/backup.sh
scripts/restore.sh

Two slight changes to backup behaviors
- Ignore backup archives
- Use `find | xargs` to gracefully handle missing files
Closes #497 
Current release backup script aborts on missing files, which an occur under normal operation. For instance if logrotate has not created any .gz files, or if the device has not connected to the grid.
I manually ran this new version of `backup.sh` to create a backup, then extracted the backup. This was test was performed on macOS 10.15.
I actually can't find the style guide anywhere.

Ignore backup archives. Use 'find | xargs' to handle missing files.

---

pwnagotchi/plugins/default/memtemp.py

Fixes the coordinates for memtemp plugin on inky display
Fixes memtemp display bug on inky display
#532
Tested both vertical and horizontal config.
Tested on pi zero w with inkyphat (black) display.  pwnagotchi version 1.2.1

fixed memtemp location for inky display

---

pwnagotchi/agent.py
pwnagotchi/defaults.yml

Add support to the `main.whitelist` option to filter by BSSID and Vendor BSSID.
See issue https://github.com/evilsocket/pwnagotchi/issues/491 for context.
Add support to the `main.whitelist` option to filter by BSSID and Vendor BSSID.
For example:
```yaml
main:
whitelist:
- EXAMPLE_NETWORK
- ANOTHER_EXAMPLE_NETWORK
- fo:od:ba:be:fo:od   # BSSID
- fo:od:ba            # Vendor BSSID
```
Tested on an ubuntu 18.04, I can confirm that both `xx:xx:xx:xx:xx:xx` and `xx:xx:xx` formats are working.
- [] My change requires a change to the documentation.

Add support to whitelist by MAC and MAC vendor

---

scripts/backup.sh
scripts/restore.sh

Signed-off-by: Aaron Bieber <aaron@bolddaemon.com>
Compatibility / Usability fixes for backup / restore scripts.
This removes the hard dependency on `bash` and adds `getopts` flags to the backup / restore scripts.
Removal of `bash` because there are simple scripts (no need for bash specific features), and not all systems ship with bash by default.
Personally I can't remember the order of things like `$1`, `$2`, so every time I backup I have to view the scripts.
Backups and restores have been done.

Make backup / restore use POSIX shell for portability.

---

scripts/backup.sh
scripts/restore.sh

Signed-off-by: Aaron Bieber <aaron@bolddaemon.com>
This fixes bugs introduced by https://github.com/evilsocket/pwnagotchi/pull/580
I have confirmed that Ubuntu (dash - thanks to @kovachwt), macOS (zsh), and OpenBSD (ksh) work as expected.

Remove '-w' as macOS doesn't have it. Fix var expansion in dash.

---

pwnagotchi/ui/components.py

to display things such as the gps coordinates in small fonts, the spacing between label and value is a little too large if we consider the limited space available on the screen.
Demo usage with gps coordinates... left new, right old - **just look at the space between the lat label & value**, the others are fakes with whitespaces...

make label to value space configurable to better fit small fonts

---

pwnagotchi/plugins/default/webgpsmap.py

Allows for negative latitude and longitude values in webgpsmap plugin
Fixed a check in webgpsmap plugin that did not allow negative latitude and longitude values
#611 
Loaded webgpsmap plugin with negative longitude values in geo.json files

webgpsmap plugin - fixed check for nonzero lat/long

---

pwnagotchi/plugins/default/gps.py

make the gps coordinates label-value more narrow to save some space. possible since  #605

decrease spacing in gps ui

---

pwnagotchi/defaults.yml

Before, paw-gps was set as pawgps in the config, this was different than the filename (paw-gps.py) so it didnt work, this request should fix that. (if this is the place that sets /etc/pwnagotchi/default.yml, this is my first PR so sorry im dumb)
Tested on my own unit, pawgps starts now, before it didnt.
rpi0w, waveshare v2, android phone with pawgps set up.
It shouldnt affect anything else its just a change to default.yml lol

Fixed Paw-Gps config, added a - mark

---

scripts/backup.sh
scripts/restore.sh

I noticed that running the backup script with no parameters caused the script to log into the pi as my current username instead of 'pi', which is probably not what most people running a default pwnagotchi install will want. This is caused by $USERNAME being defined already in the default environment of most linux shells. This change dis-ambiguates the variable name into $UNIT_USERNAME instead to avoid clashing.
Default install friendly defaults are nice :)
Ran the script before the change, it tried to log in as my current user. Tried again after the change, and it correctly logged in as 'pi' and backed up my shtuff.

fix: don't use $USERNAME as default username for backup/restore scripts, as this is usually defined on linux hosts as the current logged in user

---

pwnagotchi/plugins/default/memtemp.py

- Fix the temperature symbol when using something other than celsius (https://github.com/evilsocket/pwnagotchi/issues/616)
- Add defaults so we don't throw an exception if an invalid scale is
selected. Bad things happen if you spell fahrenheit wrong.

Fix for issue #616

---

pwnagotchi/plugins/default/led.py

I noticed that the led plugin was causing the LED to be off after every blink pattern was completed. Looks like this was caused by the /sys/class/led/led0/brightness file expecting 0 to turn the led on and 1 to turn the led off. Very strange, but this PR "fixes" the logic.
Ran the new code and observed that the LED stays on after blink patterns are complete, as one would probably want (otherwise you can't even tell if the pi is on!)

fix: apparently for the led, 0 is ON and 1 is OFF

---

pwnagotchi/plugins/default/webgpsmap.py

problem on timestamp parsing if microseconds are more then 6 numbers.
will fix bug reported in this pr: https://github.com/evilsocket/pwnagotchi/pull/619
tested with testdata from https://github.com/xenDE/pwnagotchi-plugin-webgpsmap/tree/master/handshakes.gps-map-test
before:
```
[2019-11-19 00:37:51,946] [INFO] webgpsmap: scanning /root/handshakes.gps-map-test
[2019-11-19 00:37:52,022] [INFO] webgpsmap: Found 4 .(geo|gps).json files from 5 handshakes. Fetching positions ...
[2019-11-19 00:37:52,144] [ERROR] Lng is 0
[2019-11-19 00:37:52,241] [ERROR] Invalid isoformat string: '2019-11-14T12:30:41.097414739+01:00'
[2019-11-19 00:37:52,280] [ERROR] Lng is 0
[2019-11-19 00:37:52,329] [INFO] webgpsmap loaded 2 positions
```
after:
```
[2019-11-19 00:48:04,652] [INFO] webgpsmap: scanning …
```

fix gps iso-datetime parsing

---

scripts/backup.sh

1. chmod +x backup.sh
2. ./backup.sh
3. extract 10.0.0.2-backup-1574135004.tgz
4. looking at 10.0.0.2-backup-1574135004/ no files with 0 Bytes into the folders

fix backup.sh (find with type f for no zero byte files into archive)

---

pwnagotchi/plugins/default/gpio_buttons.py

fixes handling gpio-id as string from config
fixes: https://github.com/evilsocket/pwnagotchi/issues/643

fix gpio_buttons plugin: gpio needs to be a number

---

pwnagotchi/plugins/default/grid.py

Due to duplicate entries in `/root/.api-report.json`, [this code](https://github.com/evilsocket/pwnagotchi/blob/master/pwnagotchi/plugins/default/grid.py#L90) incorrectly reports the number of pwned networks, resulting in incorrect stats on the [pwnagotchi.ai website](https://pwnagotchi.ai/). This PR fixes that problem by adding a check that the entries to be added don't already exist.
- [#657] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))
I cleared my `/root/.api-report.json` using:
```python3
import json
with open(’.api-report.json’) as json_file:
data = json.load(json_file)
print( "Entries before: " + str(len(data[‘reported’])))
data = list(dict.fromkeys(data[‘reported’]))
print( "Entries with no …
```

[BUGFIX] Prevent duplicate entries for reported networks

---

pwnagotchi/plugins/__init__.py
pwnagotchi/plugins/default/bt-tether.py
pwnagotchi/plugins/default/example.py
pwnagotchi/ui/web/handler.py
pwnagotchi/ui/web/static/css/style.css
pwnagotchi/ui/web/templates/base.html
pwnagotchi/ui/web/templates/plugins.html

This PR adds:
- /plugins site which can be used to enable/disable plugins
- on_unload event (triggered when plugin gets disabled; can be used to remove ui elements or to save data)
- database variable which contains all plugins (database[name]-> filename)

Add plugins page

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/wpa-sec.py

See #651 
If the `download_results` option is set to `true`, the results are downloaded every hour into the `wpa-sec.cracked.potfile` file.

Add wpa-sec password download

---

pwnagotchi/plugins/default/example.py

Signed-off-by: Casey Diemel <diemelcw@gmail.com>
adds ability to review an unfiltered list of APs, in a plugin, that have been detected for further processing.  Code that was not added with previous pull request/issue that was raised. 
Added `on_unfiltered_ap_list' to example.py
#668 - issue to add on_unfiltered_ap_list to example.py
#285 - merge to add on_unfiltered_ap_list to agent.py
#270 - discussion about adding to agent.py

added on_unfiltered_wifi_list

---

pwnagotchi/plugins/default/onlinehashcrack.py

For the same reasons like described here https://github.com/evilsocket/pwnagotchi/issues/657 duplicated entries could be created in /root/.ohc_uploads
I added a check if pcap name is already in /root/.ohc_uploads before the file is updated
Since plugin event handlers are running asynchronously in some circumstances there could be multiple entries created for the same pcap
After updating the code locally, I cleared file /root/.ohc_uploads and reuploaded all handshakes - getting the right number of entries stored in the file
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [ x] I have signed-off my commits with `git …

fix: Prevent duplicate entries for uploaded pcaps

---

pwnagotchi/ui/web/static/css/style.css
pwnagotchi/ui/web/templates/plugins.html

Improved display style of different plugins
Instead of displaying the plugins in a single column, I modified the "style.css" file so that the plugins are displayed in boxes on several lines.
I did not propose this modification before make the pull request, I hope that it does not pose a problem.
The tests were done in Chrome and Firefox browsers on PC and Oneplus 3T smartphone.

improvement of the plugins web page

---

pwnagotchi/voice.py

Added text overflow checking for over 999 associations
Changed code so that if a pwnagotchi enters manual mode with over 999 associations it doesn't overflow the text screen. 
Resolved Issue #634

Added text overflow checking for over 999 associations

---

pwnagotchi/plugins/default/webgpsmap.py

fix timezone "Z": "2019-11-28T04:44:46.79231Z" >> "2019-11-28T04:44:46.79231+00:00"
fix for issue: https://github.com/evilsocket/pwnagotchi/issues/708
tested with testdata at https://github.com/xenDE/pwnagotchi-plugin-webgpsmap/tree/master/handshakes.gps-map-test

webgpsmap: fix parsing new timezone format "Z" in gps data

---

pwnagotchi/plugins/default/memtemp.py
pwnagotchi/ui/hw/waveshare27inch.py

Added correct potision in memtemp.py
Fixed the config screen name in waveshare27inch.py. So far, the is_waveshare27inch() function always returned false.
pwnagotchi messages overlap with the memtemp text which makes temp unreadable.
#726 #702
This has been tested directly on a raspberry pi zero, using the standard pwnagotchi image and a physical waveshare27inch screen.

Set correct position for memtemp plugin so that it does not overlap with regular messages for waveshare27inch.

---

requirements.txt

We need to add scipy to the requirements.txt. Otherwise it will try to install the newest version, which isn't available on piwheels.org. pip will therefore (try to) compile it, which takes yeeearrs :(

Add scipy to requirements.txt

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/ups_lite.py

When the battery level comes below a certain %, auto-shutdown to prevent loosing data.
https://github.com/evilsocket/pwnagotchi/issues/650#issue-528008477
Setting the threshold way too high, and seeing it go down.

ups_lite: Add auto-shutdown

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/__init__.py
pwnagotchi/plugins/default/switcher.py

See https://community.pwnagotchi.ai/t/switcher-plugin/654
**Description:**
With this plugin you can add **tasks** which will be executed when certain **states** are reached. The main idea was to do something else when the **bored** or **sad** state is reached. In this case, pwnagotchi should do something else. After X minutes, he should start pwning again.
The configuration looks like this:
```yaml
switcher:
enabled: true
tasks:
bored:
enabled: true
reboot: true
commands:
- systemctl start fisch # see https://github.com/dadav/fisch
stopwatch: 15 # timeout of the task (in minutes)
```
In this example, the trigger of the task is the **bored** state. The **reboot** option states, that raspberry should be reboot, before executing the task (and afterwards reboot again). The **commands** option …

Add switcher plugin

---

pwnagotchi/plugins/default/webgpsmap.html
pwnagotchi/plugins/default/webgpsmap.py

now it's possible to download the map as one Html file for local use on your pc or host somewhere for mobile use without your pownagotchi.
uri: /plugins/webgpsmap/offlinemap
brings "save as" in your browser
and
use the browsers geolocation function to get the current location, show a marker and center the map there.
on success (user allows usage of get-current-position) it gets position every 30s and repositions the marker without center the map to the marker.

webgpsmap: add function for download the map as one html file and show current position on map

---

requirements.txt

This resolves #749 by removing the Crypto dependency and replacing it with Pycryptodome - as suggested in the issue.
It gets pwnagotchi one step closer to being able to be built and installed on Linux x86_64 out of the box, and is a simple fix as already documented in #749 
By running `pip3 uninstall crypto && pip3 install -r requirements.txt` on a Fedora x86_64 laptop, and then running `pwnagotchi`.

fix incorrect dependency for Crypto

---

builder/data/etc/systemd/system/pwnagotchi.service

Fix #762 
This should fix the mentioned issue. The files will still be created, but under /tmp, which will be cleaned after reboot.

Prevents permanent tfevent files

---

Makefile

As in title, also packer 1.5+ is not yet supported by the packer-builder, but this is a WIP, see:
https://github.com/solo-io/packer-builder-arm-image/issues/41
It makes Packer easier to maintain.
#766
make install
Signed-off-by: foreign-sub <51928805+foreign-sub@users.noreply.github.com>

Add PACKER_VERSION to Makefile, bump packer to 1.4.5

---

bin/pwnagotchi
pwnagotchi/ui/hw/libs/dfrobot/dfrobot_epaper.py
pwnagotchi/utils.py

This resolves #789 by replacing all `exit` builtins with `sys.exit`.
According to the [Python documentation](https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module), it is best practice to use `sys.exit` and avoid errors in programs such as PyInstaller (pyinstaller/pyinstaller#1687).
By running `pip3 install -r requirements.txt` on a Raspbian 10 Docker container and then running `pwnagotchi`.

Use "sys.exit" instead of "exit" builtin

---

pwnagotchi/utils.py

While converting the old yaml config to toml, the keys must be str. Int-keys raise an exception while dumping the toml config.

Convert keys to str

---

setup.py

This resolves #794 by reading and using the `PWNAGOTCHI_ENABLE_INSTALLER` environment variable in `setup.py`.
In some cases you want to install Pwnagotchi without making any modifications to the system, for example while being inside a virtual environment.
By running `pip3 install ./` with the `PWNAGOTCHI_ENABLE_INSTALLER` environment variable with values `true`, `false` and unset and observing that the behavior is as expected.

Allow installer deactivation

---

pwnagotchi/defaults.toml
pwnagotchi/plugins/default/session-stats.py

This will enable you to view old sessions of your runs.
I also changed the looks a bit.
It was neccesary to add a `GhettoClock`, which is just a thread that keeps track of the time, because if ntp updates the system-clock, the session data is fcked up.
Works best with the new tmpfs functionality (#806)

add session functionality to session-stats

---

pwnagotchi/plugins/default/net-pos.py

now its possible to set an own api_url in config:
[main.plugins.net-pos]
enabled = true
api_key = "test"
api_url = "https://location.services.my-own.com/v1/geolocate?key={api}"
request: https://github.com/evilsocket/pwnagotchi/issues/760

net-pos: make api_url configurable

---

bin/pwnagotchi
builder/pwnagotchi.yml
pwnagotchi/__init__.py
pwnagotchi/defaults.toml
pwnagotchi/fs/__init__.py
pwnagotchi/log.py
pwnagotchi/ui/web/__init__.py
pwnagotchi/utils.py

- **log2ram**: You can mount a directory of your choice in memory and sync it with the sdcard on an interval you choose.
E.g. if you want to mount /var/log to memory and sync it every 60s to disk:
```toml
fs.memory.mounts.log.enabled = true
fs.memory.mounts.log.mount = "/var/log"
fs.memory.mounts.log.size = "50M"
fs.memory.mounts.log.sync = 60
fs.memory.mounts.log.zram = true
fs.memory.mounts.log.rsync = true
```
You **should use** rsync, because we don't want to copy the whole directory everytime back, we want to copy only the new stuff.
You **should use** zram, because...**compression is great**? It will use lz4 as a compression algorithm, which usually will result in a 2:1 compression ratio :D The disksize will be double the `size` value, which will be the max. size that will be in …

add log2mem functionality and refracture

---

builder/data/etc/systemd/system/pwnagotchi.service

As we have our own logfile, we don't need double logging.

Disable logging to journald

---

pwnagotchi/plugins/default/gps.py

Positioned the gps labels correctly on inkyphat displays
Positioned the gps labels correctly on inkyphat displays, as they were positioned too far left and high up which overlapped with the standard pwnagotchi output.
Fixed GPS labels overlapping with standard pwnagotchi output.
Tested on my own pwnagotchi with an inkyphat display and GPS module running latest.

Fix for gps labels on inkyphat displays

---

builder/data/etc/systemd/system/pwnagotchi.service

Fixes #823 where typo causes journal logging still being enabled. Simply changes the systemd unit for pwnagotchi, fixing typo in `StandardOutput` and `StandardError` directives.
23616095baa043fc8029bde327e175d5f4e4afe7 was pushed to disable journal logging but there was typos, therefore journal logging continues on newly build/flashed images.
Fixes #823
Tested live on fresh pwnagotchi v1.4.3 image on a Pi0W with a Waveshare v2 e-paper hat.

Fix typo in systemd service to disable journal logging

---

pwnagotchi/ui/view.py

Signed-off-by: xBelladonna <isabelladonnamoore@users.noreply.github.com>
Fixes the display startup sequence bug described in #814
Triggers an update of the UI which appeared to be missing.
Described in issue #814
Tested live on a pwnagotchi running a 1.4.3 image on a Raspberry Pi Zero W with a Waveshare v2 display.

Fix hardware display startup sequence

---

pwnagotchi/plugins/default/gps.py

Currently the gps plugin creates a .gps file even if no coordinates are found. This PR prevents this.
See https://github.com/evilsocket/pwnagotchi/issues/761
Tested it locally. Works for me.

Prevent saving gps file without coordinates

---

pwnagotchi/plugins/default/onlinehashcrack.py

As explained in #820, onlinehashcrack plugin is not fully compatible with webgpsmap plugin.
This PR is a suggestion/sample to show how to fix it.
This update add an option "single_files: true" to be added into config.xml (into the onlinehashcrack section) to enable the new feature.
I tested replacing onlinehashcrack.py file in /usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/default/ and it seems working well

Onlinehashcrack should create .pcap.cracked files

---

pwnagotchi/plugins/default/gps.py

Coordinates for dfrobot v2 screens. If not lat, long, and alt are not displayed in the right locations.
This solves the issue of not displaying GPS info in the right location of the screen.
Made the changes. Ran `sudo pip3 install .` and restarted the pwnagotchi service. Fields are in a way better location than they were before.

Display coordinates for dfrobotv2

---

scripts/linux_connection_share.sh

added a line to linux script to stop running the scripts in the event that any line returns a non-zero status
added a line to linux script that stops running the scripts in the event that any line returns a non-zero status
This change helps prevent invoking changes to iptables if something is wrong ahead of time
I have run this script while not understanding what it does.  The first argument gets set as USB_IFACE.  When line 14 (`ip addr add "$USB_IFACE_IP/24" dev "$USB_IFACE"`) fails, then the subsequent lines are not run.  This is desireable b/c the next lines include altering iptables rules.
https://www.howtogeek.com/668503/how-to-set-environment-variables-in-bash-on-linux/

If a step fails, abort script.

---

pwnagotchi/__init__.py

Sync filesystem memory cache before reboot so that logs and other memory-cached filesystem changes aren't lost.
Fixes #873
Copied code from shutdown subroutine so that fs.mounts are synced prior to system reboot.
Tested on my RPi0 pwnagotchi.

Ensure fs is synced before reboot so logs aren't lost

---

pwnagotchi/__init__.py

Delay filesystem sync until just before shutdown so that "shutting down ..." message is logged to disk when memory caching is enabled.
Fixes #871 
Moved fs.mounts sync() loop until just before shutdown halt occurs.
Tested on my RPi0 pwnagotchi.

Delaying fs sync to ensure shutdown message is logged to disk

---

pwnagotchi/ui/hw/inky.py

This patch adds support for auto-detecting and using them when "ui.display.color" is set to "auto".
We (that is, Pimoroni) released a set of Inky display variants which are virtually indistinguishable from their predecessors visually, but functionally incompatible due to a change of driver IC and resolution. I gave a heads up in #941.
We include an EEPROM to ID our boards. Running `python3 -m inky.eeprom` should show display variant. Variants 10, 11 and 12 are SSD1608 based. This change uses that EEPROM, plus a new "auto" choice for "ui.display.color" to support existing and perhaps even future Inky displays without the need for future modifications to pwnagotchi.
Should fix #980 and #941
This is wholly untested and thus raised as a *draft* (I'm still stuck on the end of a kitchen table …

Add support for SSD1608 variant 250x122 pixel Inky pHATs

---

pwnagotchi/defaults.toml
pwnagotchi/plugins/default/wigle.py

Adds a new 'donate' option to allow Wigle to include data for commercial use.
Another small change: thos changes data header to reflect this is a pwnagotchi plugin, so we get credited outside 'kismet' on the [stats page](https://wigle.net/stats#androidstats).
Fixes #928 
I don't have a test device with me, though the changes are small enough I don't foresee any issues. If you find otherwise please let me know and I will do my best to update.

Add donate option to Wigle plugin

---

pwnagotchi/plugins/default/gps.py
pwnagotchi/plugins/default/memtemp.py

**Added CPU frequency**
I believe this is useful data to have as an option. It's not enabled by default but users can configure it through settings as one of the three fields shown in the plugin (see below).
**Made field types and order configurable (max 3 fields)**
The field types and order of the fields has been made configurable through `main.plugins.memtemp.fields`. If a user prefers to use `"cpu,temp,freq"` or `"mem,freq,cpu"` then they can configure this accordingly in the settings. The `fields` config setting takes a comma separate list of field names. Whitespace is stripped in the code. Default value is `"mem,cpu,temp"`.
**Made line spacing and position configurable**
Some users might prefer to slightly tweak the position or the vertical line spacing of the UI element for their …

Add configuration options to memtemp.py (fields, position, vertical line spacing)

---

builder/data/etc/network/interfaces.d/usb0-cfg

Resolves an issue where IPv4 traffic would not work when eth0 is connected (i.e. usb-ethernet adapter over OTG). The static route for usb0 precedes the DHCP route for eth0. Only IPv6 traffic would work, but not IPv4 until the metric for usb0 is increase and thus lowered in priority. If no eth0 is plugged in, internet works fine over usb0.
Add metric 20 to usb0
fixes https://github.com/evilsocket/pwnagotchi/issues/908
Edited on a running RPi W. Without the change IPv4 ping does not work. With the added line and after a reboot, IPv4 ping works.

Make sure IPv4 works when eth0 is connected

---

pwnagotchi/plugins/default/watchdog.py

The watchdog plugin detects the blindbug and restarts the application to fix the problem. Unfortunately its detection method relies on the kernel log changing so it doesn't constantly detect the blindbug. Rebooting the system instead of just restarting the application ensures that the kernel log is cleared.
Rebooting might also provide a better fix for the blindbug but this hasn't been tested.
Fixes #875
Replace call to pwnagotchi.restart with pwnagotchi.reboot.
Tested on my RPi0 pwnagotchi.

Have watchdog plugin reboot system rather than restart application

---

builder/pwnagotchi.yml

I had the same issues that are described in #902 I also came across this post to resolve a similar issue: https://community.pwnagotchi.ai/t/serial-uart-not-working-on-gpio-14-and-gpio-15/306/6
The drivers for the e-ink waveshare v2 display tie up the GPIO pins 14 and 15, which the display does not need to work. Because the drivers tie up those pins it makes it very hard to use a serial GPS device while also using the display. 
Fixes #902
I went though the process of building a fresh pwnagotchi raspberry pi image to pre-build everything. I then loaded the img on to an SD card and turned on SPI, Serial and adjusted the pwnagotchi configs to use the waveshare_2 display and GPS plugin. 
I have not tested this past gathering a few handshakes and verifying that the serial GPS and WaveShare …

swap out header file for one that doesn't tie up gpio pins 14 and 15 for waveshare_2

---

pwnagotchi/plugins/default/ups_lite.py

Replace the '%' in the battery indicator with '⚡' when the UPS-Lite is connected to an external power source.
Suggestions welcome for a different character as '⚡' is a little hard to read on e-ink displays.

Display UPS-Lite charging status

---

bin/pwnagotchi

It has come up in several community threads that when attempting to use the wifi adapter to connect to a network, even after pausing Bettercap, the main loop will continue to call `agent.recon()`, causing a JSON decoding exception to be thrown with no chance to recover.
This change allows the main loop to continue running, just with a pause, but by advancing to the next epoch, it triggers all the normal plugin hooks so that plugin code will have an opportunity to restart Bettercap once the wifi adapter can be freed up.
Addresses this issue: https://github.com/evilsocket/pwnagotchi/issues/207
Tested on Raspberry Pi Zero W with pwnagotchi 1.5.5. Tested with a custom plugin that manipulates the availability of the wifi adapter, then restores the Bettercap wifi recon after disconnecting wifi. …

catches wifi down exception and cycles epoch

---

builder/pwnagotchi.yml

this provides an ansible configuration stanza to create the kali.pref
which will prefer bootloader/kernel/libraspberrypi0 from  kali instead of debian
Creates  /etc/apt/preferences.d/kali.pref
pins the packages for the kali-pi repository to be preferred over non-kali-pi repos
This resolves issues with system updates and bootloader/kernel/libraspberrypi0 dependencies.
Without this change, the generic repo would overwrite the kernel and bootloader, as well as libraspberrypi packages,
which breaks the functionality of pwnagotchi.
With this change,  'apt full-upgrade'  works as expected, and does not break the system.
- [X ] I have raised an issue to propose this change (  #1057 )
Tested manually.   
Also tested using the script https://github.com/isthisausername2/pwnagotchi_rpi_zero_2_fix

resolve issue #1057

---

builder/data/usr/bin/pwnlib

Ensure wpa_supplicant logs to syslog
After enabling encryption as described in the documentation I noticed that every so often the `DECRYPT_ME` hotspot is not started. 
Currently wpa_supplicant does not log to its own file or syslog so this issue is hard to pin down. Having wpa_supplicant log to syslog allows for some troubleshooting
https://github.com/evilsocket/pwnagotchi/issues/1055
Manually updated wpa_supplicant command in pwnlib with additional flags (`-u -s -O`) and rebooted. wpa_supplicant now logs to syslog.

Ensure wpa_supplicant logs to syslog

---

pwnagotchi/ui/display.py
pwnagotchi/ui/hw/__init__.py
pwnagotchi/ui/hw/libs/waveshare/v3/epd2in13_V3.py
pwnagotchi/ui/hw/libs/waveshare/v3/epdconfig.py
pwnagotchi/ui/hw/waveshare3.py
pwnagotchi/utils.py

Adds support for the V3 Rev2.1 of the Waveshare 2.13inch PHAT.
[Waveshare seems to be phasing out V2 and replacing it with V3](https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT), according to their docs:
> Due to the chip upgrade, the 2.13inch e-Paper V2 will be upgraded to the 2.13inch e-Paper V3 version. The new and old demos are not compatible. Comparing the V3 version with the V2 version, in addition to the chip and driver demo, other appearances and functions are compatible. If you are an old customer and need to purchase a new screen again, please pay attention to the update program. If you are purchasing for the first time, and there is a V3 label on the back of the screen, just use the V3 demo directly. (December 2021)
This PR introduces support for the V3 screen
The library …

Add support for Waveshare 2.13inch V3 Rev2.1

---

pwnagotchi/log.py

This commit deletes the original moved logfile after compression.
os.remove at the end of log rotation
The current rotation keeps the logfiles which quickly fills up any
zram compressed log mounts which will cause the pwnagotchi to hang.
#1047 
- added line to log.py
- artificially filled pwnagotchi.log above threshold
- restarted to initiate rotation
- pwnagotchi-XX.gz exists, uncompressed log missing
1.5.5 updated

delete old log after rotation

---

pwnagotchi/defaults.toml

Adds back defaults for the ups_lite plugin that currently are not present in the default.toml
The default.toml currently does not have the required settings for the ups_lite plugin. This will throw the following error if the plugin is enabled and no additional changes are made to the config.toml.
```
Unhandled exception in thread started by <function locked_cb at 0xb651b270>
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/__init__.py", line 85, in locked_cb
cb(*args, *kwargs)
File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/default/ups_lite.py", line 83, in on_ui_update
if capacity <= self.options['shutdown']:
KeyError: 'shutdown'
```
Plugin should 'just' work using default settings after enabling and not require …

Adds back ups_lite plugin defaults to default.toml

---

pwnagotchi/plugins/default/wigle.py

Added additional checks to if clause to allow wigle.py to take into account .geo.json and .paw-gps.json files. Paw-gps,json files are formated as .gps.json files but for .geo.json files I added additional logic to format them rightly. Geo.json files also dont have altitude value, so I hardcoded it to 10m.
This was proposed by someone in the Issues so i took it upon myself to make it happen.
This was tested on Pwnagotchi version 1.5.5 that uses RPi0W. It correctly formats and sends data to wigle.py.

Enabled wigle to use .geo.json and .paw-gps.json files

---

pwnagotchi/ui/hw/oledhat.py

Better positioning of ui elements for the small Waveshare 128x64px OLED HAT display (SH1106)
When I first tried to use the display, I thought to play with the font or its size, but I ended up just slightly rearranging the ui elements a little to avoid numerous overlaps present in the upstream version.

Better ui elements for Waveshare 128x64px OLED

---

pwnagotchi/defaults.toml
pwnagotchi/plugins/default/paw-gps.py

Ensures sane defaults are used for paw-gps plugin.
Implements additional check for the value of `self.options['ip']` to avoid empty strings breaking the plugin.
Implements error handling for more detailed error logs.
The default.toml file contains the following default value for the IP of paw-gps `plugin main.plugins.paw-gps.ip = ""`.
The current plugin uses the following logic to determine what value it should use by default. This logic does not handle the default empty string, meaning IP is never set to the intended default value.
```python
def on_loaded(self):
logging.info("PAW-GPS loaded")
if 'ip' not in self.options or ('ip' in self.options and self.options['ip'] is None):
logging.info("PAW-GPS: No IP Address in the config file is defined, it uses the default (192.168.44.1:8080)") …
```

Ensure paw-gps works when default values are used.

---

pwnagotchi/plugins/default/gps.py

This is a very nit-pick pull request, but it could save some headaches from people trying to debug GPS errors.
When using a GPS module, `/var/log/pwnagotchi.log` shows the following entries:
```
[2021-10-19 10:34:24,998] [INFO] enabling bettercap's gps module for /dev/ttyAMA0
[2021-10-19 10:34:25,311] [INFO] error 400: module gps is not running
[2021-10-19 10:35:07,271] [INFO] sending association frame to TP-Link_2334...
```
that `error 400 module GPS is not running` comes from a handled exception inside the `on_ready` function and it's a little bit weird at a first glance if you're trying to debug the GPS connection/lock-up.
closes #1041
I've just built a new image on a Raspberry PI Zero W.

plugins/gps: add some logging around the gps off exception

---

pwnagotchi/ui/display.py
pwnagotchi/ui/hw/__init__.py
pwnagotchi/ui/hw/waveshare35lcd.py
pwnagotchi/utils.py

Added config file for 3,5" Waveshare display
Tested with my  raspi4 (4gb) an the waveshare 3,5" display

Add Display support for Waveshare 3,5" (and clones) framebuffer lcd.

---

pwnagotchi/ui/display.py
pwnagotchi/ui/hw/__init__.py
pwnagotchi/ui/hw/adafruitssd1306i2c.py
pwnagotchi/ui/hw/libs/adafruit/adafruitssd1306i2c/SSD1306.py
pwnagotchi/ui/hw/libs/adafruit/adafruitssd1306i2c/epd.py
pwnagotchi/utils.py

I had one of the generic SSD1306 lying around, one night I decided to try pwnagotchi out with my pi 0 w, for the lack of any other display at hand on a weekend night, I thought of porting this display.
Currently there's no support for the SSD1306(popularly known as the [Adafruit Monochrome Oled 0.96"](https://www.adafruit.com/product/326)") which is a very accessible and cheap display, lots of hobbyist have it handy already, due to the countless unofficial ones flooding around in the market.
Resolves Issues: #1257 #1256 
Updated display changes were manually copied over to a fresh build of pwnagotchi v1.5.5 at location /usr/local/lib/python3.7/dist-packages/pwnagotchi with updated config.toml settings pointing to the new display, logs have been checked, both manual and auto mode has been …

Add support for Adafruit SSD1306 i2c Oled Display 128*64
