evilsocket/pwnagotchi

.gitignore
README.md
create_sibling.sh

I automated the image creation process in a small script. It uses the qemu-user-static method you mentioned in your tweet.
All you need now is:
`./create_sibling.sh -n beta -o pwnagotchi-beta.img `
It will use the latest raspbian.
It would be good if someone could test the output on a pi, cuz i need to order another sdcard first ^.^

Add image creation script

---

.gitignore
scripts/create_sibling.sh

Found some bugs. Also, script must be run as root now, because we did everything with sudo anyway. Because the script was moved into scripts-dir, it was creating stuff in this directory.

Script improvement and bugfixes

---

scripts/create_sibling.sh

For people that are testing and don't want to download it again.

Added ability to provide path to raspbian.img

---

README.md
scripts/create_sibling.sh

I fixed the bugs which were mentioned in the other PR (#7 )
AI should also work now out of the box.
On the first boot, tensorflow and opencv will be reinstalled in the correct arch, this will take about 15mins.
Your ssh credentials are pi:raspberry,
you  should change them ^^

Fixed bugs and made the script work out-of-the-box for the first time

---

.travis.yml
scripts/create_sibling.sh

Added travis-ci support.
Build takes around 45mins. It's not fast, but it works!
I added zip -s 2g because github has a 2g limit per file.

Add travis support

---

README.md

Fix grammar and path

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/voice.py

Forgot to add "self" when i changed it into a class...

Add some forgotten selfs

---

scripts/preview.py

The former version is dangerous and destroys effectively V1-Displays.

Update main.py to use correct displays for --clear

---

scripts/preview.py

Missed some this afternoon, here is the rest^^

Add rest of emotions

---

.travis.yml
Makefile
builder/pwnagotchi.json
builder/pwnagotchi.yml

This version does not include the repository cleanup, I want to try to builder first on travis before merging/cleaning up.
To avoid too many changes at once.

initial packer/ansible base builder

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/ui/waveshare/v1/epd2in13.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/ui/waveshare/v1/epdconfig.py

from: https://github.com/waveshare/e-Paper/tree/master/RaspberryPi%26JetsonNano/python/lib/waveshare_epd
This triggers the CS PIN so that the signalling is cleaner resulting in more fresh refreshes.
Note that one should look at the diff with '-w' (ignore whitespace) as waveshare does not really do nice diffs...

Update waveshare v1 driver to "4.00" aka "2019.07.31"

---

scripts/create_sibling.sh

Oversight when adding the original OPT_SPARSE
Addresses #56

The -S option does not exist, as it is automatically detected (OPT_SPARSE)

---

.DEREK.yml

Derek is a bot that will allow us to manage PRs and Issues without needing access to the repository.
It allows us to assign labels, users and a lot of other features https://reaxt.com/alexellis/derek/blob/master/USER_GUIDE.md
@evilsocket you will need to add the derek app to your repo https://github.com/apps/derek

Adds .DEREK.yml

---

scripts/update_pwnagotchi.sh

https://github.com/evilsocket/pwnagotchi/issues/69#issue-501710314
I won't decide if it should be a separate option by itself, but I personally think they do go hand in hand in this context.

added hostname backup and restore

---

.travis.yml
Makefile
builder/pwnagotchi.json
builder/pwnagotchi.yml

* PLEASE DON'T MERGE THIS UNTIL TRAVIS INTEGRATION IS FUNCTIONAL *

new builder system based on packer/ansible

---

sdcard/rootfs/etc/rc.local

For some reason this if was not added during my PR.

Add the check if HDMI cable is connected

---

.travis.yml

This pr forces travis to only run on branches or tags that match an specific regrexp /^v[0-9]+\.[0-9]+\.[0-9]+$/
So to trigger a new release, a tag in the format of vX.X.X needs to be added, ideally this will be added to the master branch by @evilsocket when he wants to do a new release.

change .travis.yml configuration

---

.travis.yml

Fix cache bug

---

.travis.yml

So that we can continue testing^^

Fix psql repo fail

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

As Hacktoberfest approaches, it would be cool to be prepared to participate.
That being said this PR adds CONTRIBUTING.md and also Issues and PR templates

add templates and CONTRIBUTING.md

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/memtemp.py

show only real ram without swap space

removed swap from shown memory

---

sdcard/rootfs/root/pwnagotchi/scripts/main.py
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/twitter.py

See #109 
The code for twitter is now a plugin and enabled by default.

Outsource twitter-code to plugin

---

scripts/create_sibling.sh

Updated Scrip to give a random gender to the baby!

Update File to randomize gender in build scripts

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/wpa-sec.py

See #107 
You need the tool wlancap2wpasec to use this tool! Installation instructions are written in the plugin. Will probably migrate to pure python in the future.

Add wpa-sec-upload plugin

---

docs/about.md

minor copyediting for typos

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/onlinehashcrack.py

With this plugin your new handshakes will be uploaded to onlinehashcrack.com :)
You just need to activate it in your config via:
```yaml
plugins:
- 'onlinehashcrack'
```
and put your email into the plugin.

New Plugin: Upload to onlinehashcrack.com

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/wpa-sec.py

Remove dependency mentioned in  #107

Upload via python library

---

sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/agent.py

There are two `start` methods in `agent.py`.

Fix name conflict

---

sdcard/rootfs/root/pwnagotchi/config.yml
sdcard/rootfs/root/pwnagotchi/scripts/pwnagotchi/plugins/default/auto-backup.py

See #139 
```yaml
plugins:                                                            
auto-backup:                                                                                                                               
enabled: false                                                                                                                           
interval: 1 # every day                                                                                                                  
files:                                                          
- /root/brain.nn                                              
commands:
- 'tar czf /tmp/backup.tar.gz {files}'                
- 'scp /tmp/backup.tar.gz 10.0.0.1:/backups/backup-$(date).tar.gz'   
```

Add auto-backup plugin

---

sdcard/rootfs/root/pwnagotchi/config.yml

Updated the list of existing translations in config.yml.
As I started on the Swedish translation I noticed that config.yml did not contain all the existing translations.
Raised issue https://github.com/evilsocket/pwnagotchi/issues/142 for this
(https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))
No real need to test - pure documentation change.
- [X ] I have updated the documentation accordingly.
- [ X] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide

Updated existing translations in config.yml

---

builder/pwnagotchi.yml

Image builder improvements
This PR includes many modifications to our ansible/packer builder to improve quality of life for our users, including no runtime install of dependencies.
This PR also enabled serial gadget mode, which enable users to connect via serial port OR ethernet to the pwnagotchi

Image builder improvements

---

builder/pwnagotchi.yml

fix typo on purge package blocks

fix typo on purge package blocks

---

docs/configure.md
sdcard/rootfs/root/pwnagotchi/config.yml

Updated so that all documentation mentions both of the two latest, Russian and Swedish, translations that have been added.
Making sure that it's documented properly.
Documentation change only - can't really be tested.
- [x ] I have updated the documentation accordingly.

More documentation updates for languages

---

builder/pwnagotchi.yml

I've put all the lists to the top and changed the variable names from the understore-style to dict-style.
pwnagotchi.hostname should be clearer than pwn_hostname

Refracture ansible playbook

---

builder/pwnagotchi.yml

This PR reverts the serial port until a fix is in place for windows users.

disable serial

---

README.md

[x] updated text of README.md to match readability of about.md text
[x] fixed "Developement" typo in TOC
[x] added hacks.md to TOC
[x] official links are now in tabular form
[x] added subreddit link
[x] added link to the **Training the AI** section of usage.md

updated main text; alpha disclaimer; added hacks.md

---

docs/faq.md

(will fill in the actual content tomorrow.)

added FAQ questions skeleton + TOC header structure

---

.gitignore
scripts/preview.py

The path to `pwnagotchi` changed and `preview.py` had to be adjusted.

Fix path to pwnagotchi

---

docs/about.md
docs/hacks.md

minor edits to docs

---

pwnagotchi/plugins/default/onlinehashcrack.py

Fix bug with gps.json files

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/wigle.py

See #110 
You can enable this plugin via:
```yaml
plugins:
wigle:
enabled: true
api_key: 'adasdasd23refgwt' # Your API-Key
```

Add wigle plugin

---

scripts/preview.py

Now you can use `--show-peer` to see how it would be to have another pwnagotchi^^

Add --show-peer to preview.py

---

README.md
docs/configure.md
docs/usage.md

- minor copyediting on configure.md
- added UI diagram to usage.md

minor copyediting on configure.md + added UI diagram to usage.md

---

pwnagotchi/plugins/default/wigle.py

- Renamed some variables
- Added some comments
- Fixed a bug (too many handshakes were marked as correctly uploaded)

Rename some vars and fix some bugs

---

README.md

See #184 
Link was going nowhere!

Fix 404 url

---

scripts/create_sibling.sh

Simple fix to improve the if cycle

Simple fix to improve the IF cycle

---

pwnagotchi/plugins/default/grid.py
pwnagotchi/plugins/default/wigle.py
pwnagotchi/utils.py

See #204 
I put the pcap-parsing in the utils.py file. This way, not every plugin has to write their own parsing.

Put pcap parsing in utils class

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/gps.py

See #199 
Added the device and speed option to default.yml and used OPTIONS-dic in gps-plugin!

Add OPTIONS to gps-plugin

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/screen_refresh.py

Plugin to refresh display every X changes
Works on mine

Plugin to refresh display every X changes

---

pwnagotchi/plugins/default/gps.py

Forgot to change some options^^

Add OPTIONS

---

pwnagotchi/plugins/default/wigle.py

See #213 
- Added a check to see if the gps-data is valid

Add gps validy check

---

builder/pwnagotchi.yml

To improve our manual mode this PRs also enabled bettercap ui on manual mode.

enable bettercap ui on manual mode

---

builder/pwnagotchi.yml

fix path and ui install

---

.travis.yml
Makefile

generate sha256sum from the generated image, add it to the release

generate sha256sum from the generated image, add it to the release

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/quickdic.py

Run a quick dictionary scan against captured handshakes as prliminary heck so when at home can do more advanced checks with masks etc.
Works on mine
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have updated the documentation accordingly.
- [ x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [?! ] I have signed-off my commits with `git commit -s`

Run a quick dictionary scan against captured handshakes

---

builder/pwnagotchi.yml
pwnagotchi/defaults.yml

add motd and defaults.yml disclaimer

---

pwnagotchi/plugins/default/grid.py

Fix typo in grid plugin

---

builder/pwnagotchi.yml

Signed-off-by: chksome <chksome@protonmail.com>

Fix motd typo and some grammar

---

pwnagotchi/plugins/default/net-pos.py
pwnagotchi/plugins/default/onlinehashcrack.py
pwnagotchi/plugins/default/wigle.py
pwnagotchi/plugins/default/wpa-sec.py

I migrated the file tracking to the StatusFile-class.
The StatusFile class is super handy to track already uploaded files. @evilsocket gave me a hint, so i migrated some plugins.
- [ x] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))
See #281 
by myself.
- [x ] Breaking change (fix or feature that would cause existing functionality to change)
The old tracking files won't work anymore, so the handshakes will be re-uploaded...

Migrate to statusfile

---

pwnagotchi/plugins/default/bt-tether.py

With the old plugin the pairing had to be done by hand. Now pwnagotchi can do it by himself!!
Also, internet-sharing (change the route + resolv.conf) has been added.
See #277 
Tested by myself.
- [x ] New feature (non-breaking change which adds functionality)

Add auto-pair and internet-sharing

---

pwnagotchi/locale/fr/LC_MESSAGES/voice.po

Added missing words for the french PO file

---

pwnagotchi/defaults.yml
pwnagotchi/ui/display.py
pwnagotchi/ui/view.py
pwnagotchi/ui/waveshare/oledhat/SH1106.py
pwnagotchi/ui/waveshare/oledhat/config.py
pwnagotchi/ui/waveshare/oledhat/epd.py

Add support for waveshare oledhat display.
Refactor view.py to have more variable to support more screen types/size in the future
This allow to use other types of screen and eventually to use hardware button to launch actions in the future.
Issue raised #291 
This has been tested with waveshare v2 and oledhat screen (to verify regression).

Add support for waveshare oledhat display.

---

pwnagotchi/ui/layout.py

Fix for layout.py to handle oledhat

---

pwnagotchi/utils.py

As by now it's a bit guessing, which parts of the config are really taken into usage. I think it'd be helpful to print out the config upon startup.
see above
Tested using a RC4 image on a Pi0W

Print effective merged config

---

pwnagotchi/plugins/default/bt-tether.py

I compared apple with oranges, this could never work... Hopefully the last patch in this topic xD

Fix str comparison and add sleep

---

pwnagotchi/ui/hw/waveshare1.py

Fix waveshare v1 layout: status pos

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/memtemp.py

Signed-off-by: spees <speeskonijn@gmail.com>
Refactored memtemp to make it actually work using the same functions that were already used to show the information in the logs. Added horizontal and vertical orientation for displaying the information.
Same as above.
memtemp didnt work for most people. Sometimes it did, sometimes it didnt. 
It has been running on my pi hours on end without problems even after reboots.

refactored memtemp so it actually works

---

pwnagotchi/defaults.yml
pwnagotchi/ui/display.py
pwnagotchi/ui/hw/__init__.py
pwnagotchi/ui/hw/libs/waveshare/v27inch/epd2in7.py
pwnagotchi/ui/hw/libs/waveshare/v27inch/epdconfig.py
pwnagotchi/ui/hw/waveshare27inch.py
pwnagotchi/utils.py

I have added the original Waveshare libraries needed for the Waveshare 2.7inch e-Paper Display and made a config file for it to work with the display
I recently bought a Waveshare 2.7inch e-Paper Display what perfectly fits my Raspberry Pi 3 model B+, without knowing it didn't work out of the box with pwnagotchi. So I went researching and added the required libraries and configurations.
I also saw 2-3 people in the slack channel #waveshare trying to get this working.
I tested it on my Raspberry Pi 3 Model B+ with the Waveshare 2.7inch e-Paper Display. I only added of/elif statements, so it does not affect other areas of code. I added the original libraries from Waveshare.
Here are some photo's of the display. https://imgur.com/a/C1RUgrc

Added support for Waveshare 2.7inch e-Paper Display

---

pwnagotchi/plugins/default/example.py
pwnagotchi/ui/web.py

Hook em up!
The idea came from daPwnie! 
Possible use cases:
- show collected gps-positions on a map (gps-plugin)
- create a chat in browser (grid)

Implement webhook for plugins

---

pwnagotchi/ui/display.py
pwnagotchi/ui/hw/libs/waveshare/v1/epd2in13bc.py

The idea is if display update takes a lot of time (~15s for waveshare v1), each epoch takes more time, so Pwnagotchi might be learning much slower. So I moved display updating to a separate thread
Also added small delay to ReadBusy, since it seems like it was slipping sometimes? (When I implemented non blocking update, I added debug logging and it was taking a fraction of a second, which seemed weird. Now I'm checking logs, and it takes 15 sec, so my guess is it might not always catch high level on a pin, but dunno)

Add non blocking display updating

---

pwnagotchi/plugins/default/bt-tether.py

Well, i rewrote some stuff and it's working way better now^^

Fix lot of bt-tether problems

---

pwnagotchi/__init__.py

Replace subprocess execution of `free` for parsing `/proc/meminfo`

parse /proc/meminfo to gather memory usage

---

pwnagotchi/plugins/default/auto-backup.py

This PR deals with #391.
Instead of simply adding all configured files I added a check to verify, if the file exists. This prevents any failures due to missing files. 
Testes on my PiZ in context of #391

#391: Verify if the configured files exist

---

pwnagotchi/plugins/default/wigle.py

There is no plural of information.
- [ x ] Bug fix (non-breaking change which fixes an issue)

Minor text fixes

---

pwnagotchi/ui/hw/libs/waveshare/v27inch/epd2in7.py
pwnagotchi/ui/hw/libs/waveshare/v27inch/epdconfig.py

Signed-off-by: Mike van der Vrugt <mimij68@live.nl>
Changed the libraries to the newest release V4.0.
I've been using V4.0 with my 3B+ and 2.7" display for at least 2 days and it works as good as the previous libraries.

Updated libraries to V4.0 for the 2.7" display

---

pwnagotchi/defaults.yml
pwnagotchi/ui/web.py
pwnagotchi/utils.py

```js
fetch('http://10.0.0.2:8080/').then(function (r) {return r.text()}).then(function (r) {console.log(r)});
```
should fail by default

Set CORS headers only if set in config

---

pwnagotchi/plugins/default/AircrackOnly.py
pwnagotchi/plugins/default/grid.py
pwnagotchi/plugins/default/paw-gps.py

Signed-off-by: Edward Medvedev <edward.medvedev@gmail.com>
This PR removes some unused imports from plugins. Not a big deal, but with something as low-powered as Pi Zero every little bit counts, I guess, and also it makes the plugin code a tiny bit cleaner. :)

Optimize plugin imports

---

pwnagotchi/defaults.yml
pwnagotchi/ui/hw/libs/waveshare/v1/epd2in13bcFAST.py
pwnagotchi/ui/hw/waveshare1.py

Waveshare 2.13in tri-color display takes about 15s to refresh. This is way too long.
I've added some code to over-drive the display, basing it off of the 2in13d driver and playing with the look-up tables to get a ~1sec refresh rate.
This is potentially dangerous, so it is added as a separate color option. 
That said: I've been testing it for a few hours now, and it hasn't broken anything, and i'm seeing almost no ghosting.
Again though, your milage may vary... this could easily destroy a screen, and it really should get a lot of testing from people who are willing and understand the possibility of their screen going poof before making it a normal option without warnings or disclaimers.
To use this, set your display to 'waveshare_v1', and set the color to 'fastAndFurious'.
Much faster …

Adding Waveshare 2.13 tri-color display FAST MODE

---

scripts/preview.py

Preview.py was crashing when run. Resolved this.
Includes configuration required to generate a preview.
Removes links to VideoHandler which is its own class
Added required method to the DummyPeer
Previews could not be used, and given the addition of more displays, it will come in useful for testing of layouts.
https://github.com/evilsocket/pwnagotchi/issues/435
Git cloned to be up to date, and ran using several displays: inky, waveshare_2, waveshare27inch
Verified generated preview.png that it matched the size and layout of the display.
Does not affect other areas of the code as preview was designed to be standalone.

Updated Preview

---

scripts/backup.sh

* **pi** is just the default on raspbian, so this should be choseable
* backup of .bashrc is some personal preference, how do you see this?
* fix shellcheck lint issues
More reliable backups and faster restore after upgrades
Testet with my two pwnagotchis ;)

polish backup.sh: add username, .bashrc to backup files, fix shellcheck lint issues

---

pwnagotchi/ui/display.py
pwnagotchi/ui/hw/__init__.py
pwnagotchi/ui/hw/libs/waveshare/v213d/epd2in13d.py
pwnagotchi/ui/hw/libs/waveshare/v213d/epdconfig.py
pwnagotchi/ui/hw/waveshare213d.py
pwnagotchi/utils.py

https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT_(D)
This one's easily available on Amazon (same day even) and is the same size as the Waveshare V2 so it should work pretty well.
Made changes and loaded it on my Pi Zero. Works great now.

add waveshare 213d display

---

bin/pwnagotchi

Now you can type `pwnagotchi --version` to get the installed version.

Add version option

---

pwnagotchi/plugins/default/bt-tether.py

When this object was collected by the gc, the connection was closed... Thats why i added a global reference.

Add reference to network object (bt-tether fix)

---

bin/pwnagotchi

With the new plugin-class, pwnagotchi gave me an error. Can't seem to get the path of the class tho

Fix debug msg to fit new plugin class

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/bt-tether.py

Added a `enabled` option for each device.
Changed the default-ip of the ios device to `172.20.10.6`.

Fix bt-tether config

---

pwnagotchi/plugins/default/onlinehashcrack.py

Added the ability to whitelist specific SSIDs or BSSIDs to prevent upload of their handshakes to OHC
Not everyone wants handshakes for their personal networks uploaded
Removed already-uploaded handshake files from /root/.ohc_uploads, added ssids to main.plugins.onlinehashcrack.whitelist, ran pwnagotchi and observed local debugging log messages verify the skipping of upload of whitelisted handshakes. then removed whitelist, restarted, and watched ohc plugin upload the previously-whitelisted handshakes as expected
https://github.com/evilsocket/pwnagotchi/issues/462

Add whitelist support to onlinehashcrack plugin

---

pwnagotchi/plugins/default/bt-tether.py

Make bt-tet less verbose

---

pwnagotchi/ui/web.py

Unblurred image rendering in browsers. Affects both desktop and mobile image rendering.
Source (https://css-tricks.com/almanac/properties/i/image-rendering/)

Unblurred image rendering in browsers

---

builder/pwnagotchi.yml
pwnagotchi/plugins/default/example.py
pwnagotchi/ui/web.py

As discussed i migrated the web.py to flask. Current security features are CORS-protection and CSRF tokens!
It's a first step we can use as a base for further improvements :)

Migrate to flask

---

pwnagotchi/plugins/default/bt-tether.py

- Fix on_loaded message
- Handle "Interface" not found exception
- Fix typo
- Changed the log-msg prefix to "BT-TETHER" instead of "BT-TET"

More bt-tether fixes

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/gpio_buttons.py

Array of dicts and usage of sudo while root...this bugged me alot

Fix options of gpio-plugin

---

pwnagotchi/defaults.yml
pwnagotchi/utils.py

Signed-off-by: Jeremy O'Brien <neutral@fastmail.com>
It doesn't crash! :D

normalize the waveshare29inch config string

---

pwnagotchi/plugins/default/example.py
pwnagotchi/ui/web/handler.py

Changed webhook arguments, added exception handling, added logrotation

---

builder/pwnagotchi.yml

fstrim timer triggers weekly to issue TRIM/DISCARD on devices that support it,
which includes SD and MMC devices.
This marks all unused diskspace as available for internal garbage collection
and wear levelling on the card.  It's preferrable to use the timer to the
discard option, as it involves a one-off cost of latency over a global slowing
down of all write or erase requests that the `discard` mount option does.
Enable the fstrim.timer unit by default, keeping upstream settings for period
Fixes long-term lifetime of SD-cards.
https://github.com/evilsocket/pwnagotchi/issues/550#issue-519387265

Enable fstrim.timer to increase SDCard lifetime

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/webgpsmap.html
pwnagotchi/plugins/default/webgpsmap.py

a plugin for pwnagotchi that shows a openstreetmap with positions of ap-handshakes in the webbrowser
http://[ip-of-your-pwnagpotchi]:8080/plugins/webgpsmap
tested on master 
tested with net-pos plugin data by daPwnie
tested with gps plugin data by dadav

added webgpsmap plugin

---

pwnagotchi/plugins/default/gps.py

fix completely broken gps plugin

---

pwnagotchi/plugins/default/gps.py

Now the gps plugin finally works ;)

fix baudrate option name in gps plugin

---

pwnagotchi/plugins/default/gps.py

shift word

---

pwnagotchi/plugins/default/ups_lite.py

Small typo fix - offset should be +15, not -15

Small UPS Lite typo fix

---

pwnagotchi/plugins/default/bt-tether.py

Well it's just a small typo correction.

Fixed a small typo in bt-tether

---

pwnagotchi/agent.py

3 new properties are exposed from the Agent class in preparation for the state-api using them in the JSON.
It would allow the core data to be provided over JSON as well as the actual text field from the display, showing more flexibility.
Have run the device in Manual/Auto/AI modes and retrieved the values from the Agent.

Providing APs/APs per channel and current channel as R/O from Agent

---

pwnagotchi/ui/display.py
pwnagotchi/ui/hw/__init__.py
pwnagotchi/ui/hw/libs/fb/fb.py
pwnagotchi/ui/hw/spotpear24inch.py
pwnagotchi/utils.py

Support for SpotPear 2,4" LCD display 
Added new display and a pure python framebuffer memory mapping library

Add support for SpotPear 2,4inch LCD display via framebuffer

---

pwnagotchi/plugins/default/ups_lite.py

fix plugin because of string formatting error
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide

small typo fix

---

pwnagotchi/locale/spa/LC_MESSAGES/voice.po

Signed-off-by: Angel <ahsec>
Followed instructions in
https://pwnagotchi.ai/contributing/#adding-a-language
to add support for Spanish language
Solves the problem of lack of support of Spanish language
Should be an isolated change as it only affects the language, however, couldn't find any unit or integration tests.
Happy to run any tests if available.
- [X ] New feature (non-breaking change which adds functionality)
- [ X] My code follows the code style of this project.
- [ X] My change requires a change to the documentation.
- [ X] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [ X] I have signed-off my commits with `git commit -s`

Adding support for Spanish language

---

pwnagotchi/plugins/default/gps.py

demo: https://twitter.com/ben_leb/status/1194311274466873345/photo/1

show gps coords of last handshake in ui

---

pwnagotchi/plugins/default/bt-tether.py

add gateway option to bt-tether

---

pwnagotchi/plugins/default/gps.py

use f-strings as they are more readable, more convenient to write and also faster.
also make use of the more python typical double quotes
there should be some guideline with a linter config or something to prevent an other code style in every plugin/file... i like the one in which is used in this plugin now. 4 spaces indent, f-strings and double quotes except when referencing an index in a double-quoted string. its the style of ```black```, see https://github.com/psf/black
example:
```python
logging.info(f"gps plugin loaded for {self.options['device']}")
```
and here the current variant for comparison
```python
logging.info("gps plugin loaded for %s" % self.options['device'])
```

f-strings and double quotes in gps plugin

---

pwnagotchi/agent.py

Signed-off-by: Wystan Schmidt <wystans@gmail.com>
Added rssi signal strength to logging messages
Addresses [#331](https://github.com/evilsocket/pwnagotchi/issues/331)
Checked logging messages with changes.

Added signal strength to logging messages

---

pwnagotchi/plugins/default/paw-gps.py

Change default ip from 192.168.44.1 (which is the ip address of an android on bt tether) to 192.168.44.1:8080 so it has the default port paw-gps opens on, which is 8080.
Just added port to paw gps probably, im not too good at this but i probably did this right
solves it so paw gps works
before paw-gps started (with my other PR #606 ) but now it actually works too.
rpi0w, waveshare v2, android 9, pawgps app.
shouldnt affect anything else

Fixes to paw-gps.py

---

pwnagotchi/plugins/default/paw-gps.py

Got permission from LeonT for this

Add link to better guide to paw-gps.py

---

pwnagotchi/plugins/default/paw-gps.py

Remove old link due to it not being too good, update file extension to .paw-gps.json for better support on problems with webgpsmap.
This makes it easier to troubleshoot problems with webgpsmap, removal of the old link makes problems due to user mistakes harder.
Tested on my own rpi0w, waveshare 2.13 v2, android 9 phone, master branch.
It should only affect paw-gps and make it create new filenames.

Update to using .paw-gps.json files

---

pwnagotchi/plugins/default/webgpsmap.py

- cleanup logging
- increase cache item count from 1024 to 2048
- add handling of corrupt long/lat position null
- added handling of .paw-gps.json files - tested with master
- add handling of old paw-gps format

cleanup, fixes and add handling of .paw-gps.json

---

pwnagotchi/plugins/default/webgpsmap.html

add a filter input box on top of the map
enter search keyword and press enter to become a filtered map

webgpsmap: add filter for: SSID, MAC, isCracked, Password

---

pwnagotchi/locale/ru/LC_MESSAGES/voice.po

Adding untranslated strings, updating some strings.
Adding untranslated strings, updating some strings.
Adding untranslated strings, updating some strings.
I read the translation carefully. 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
Signed-off-by: Evgeny Zelenin <m-b-g@yandex.ru>

Updating the Russian translation

---

pwnagotchi/ui/web/templates/plugins.html

Now every plugin - which is enabled and has the on_webhook method - will have an href.

Add urls to plugins

---

setup.py

Use list comprehension
I just made the for loop more readable, pythonic, and brief.
I tested this on a pi.

Use list comprehension in setup.py

---

pwnagotchi/plugins/default/net-pos.py

Fix #533 
+ less verbose
+ add lock

Add lock; make less verbose

---

pwnagotchi/plugins/default/bt-tether.py

Added a lock to prevent multiple running searching routines.

Add lock to bt-tether

---

pwnagotchi/agent.py

Leverage logging laziness rather than string formatting
https://docs.python.org/3/howto/logging.html#optimization describes the laziness of logging
I tested this on a pi.

Replace string formatting with logging laziness in agent.py

---

pwnagotchi/plugins/default/onlinehashcrack.py
pwnagotchi/plugins/default/wpa-sec.py

- Add lock to plugin
- small refracturing :)

Add lock to onlinehashcrack plugin

---

bin/pwnagotchi

#206 
- add usr1 handler to restart process

Add signal handler

---

pwnagotchi/defaults.yml
pwnagotchi/plugins/default/gps.py
pwnagotchi/plugins/default/memtemp.py
pwnagotchi/ui/display.py
pwnagotchi/ui/hw/__init__.py
pwnagotchi/ui/hw/libs/waveshare/lcdhat144/LCD_1in44.py
pwnagotchi/ui/hw/libs/waveshare/lcdhat144/config.py
pwnagotchi/ui/hw/libs/waveshare/lcdhat144/epd.py
pwnagotchi/ui/hw/waveshare144lcd.py
pwnagotchi/utils.py

Waveshare 1.44inch LCD HAT
https://www.waveshare.com/1.44inch-lcd-hat.htm 
https://www.waveshare.com/wiki/1.44inch_LCD_HAT
Driver: ST7735S                                
Interface: SPI                                 
Display color: RGB, 65K color                  
Resolution: 128x128                            
Backlight: LED                                 
Operating voltage: 3.3V                        
Add new display
Waveshare 1.44inch LCD HAT
https://github.com/evilsocket/pwnagotchi/issues/648
Tested at my pwnagotchi.

waveshare 1.44inch lcd hat

---

pwnagotchi/agent.py
pwnagotchi/automata.py

Unknown variable; Logic error

---

pwnagotchi/__init__.py

Replace string formatting with logging laziness in \_\_init\_\_.py. Also I removed an unused library import.
#697 
I tested it on a pi. Also I am running `pylint` this time to prevent simple mistakes.

Replace string formatting with logging laziness in __init__.py

---

pwnagotchi/agent.py

no comment

---

pwnagotchi/utils.py

add ensure_write

---

builder/data/etc/systemd/system/pwnagotchi.service

Got an error that no more new threads could be started. I think it's a cgroup error, so i increased the limits (and the limits of setrlimit).

remove process limits

---

pwnagotchi/plugins/default/gps.py
pwnagotchi/plugins/default/memtemp.py
pwnagotchi/plugins/default/ups_lite.py

This PR adds the unload method to various plugins.

add unload method

---

builder/pwnagotchi.yml

It looks like there is a typo in the name of one of the services to disable.
I do not have the skills not the setup to test it...just notice the typo while studying the code ;-)

typo (maybe)

---

pwnagotchi/defaults.toml

This resolves #791 by converting back to integer some values from `defaults.toml`.
Since the change to TOML some integers have been converted to floats and although in most cases this is not a problem the AI fails to load because it expects integers.
By running `pip3 install -r requirements.txt` on a Raspbian 10 Docker container and then running `pwnagotchi`.

Converted back to integer some values from "defaults.toml"

---

scripts/preview.py

Adjust preview.py (toml)

---

pwnagotchi/plugins/default/bt-tether.py

This fix is related to the toml-migration

Bt-Tether fix

---

pwnagotchi/__init__.py

Fix version import

---

bin/pwnagotchi

If we want to dump the config, we need the import here

fix import

---

pwnagotchi/plugins/default/webgpsmap.py

webgpsmap: better logging informations for easy user debugging

---

pwnagotchi/defaults.toml
pwnagotchi/plugins/default/onlinehashcrack.py

With this you can automatically download the cracked passwords.

add password download from onlinehashcrack

---

pwnagotchi/plugins/default/onlinehashcrack.py

Fix bug in ohc plugin

---

pwnagotchi/log.py

I was testing something and forgot to delete this

remove accidentally commited snippet

---

pwnagotchi/defaults.toml

Add single_files option to onlinehashcrack config

---

builder/pwnagotchi.yml

add dnsmasq

---

.gitignore

Add python virtual environment folders to git ignore
After git ignore was updated. I was able to create a virtual environment and git status reported my working tree clean

Ignore python virtual environments

---

pwnagotchi/plugins/default/webgpsmap.html

Why limit zoom? As a user, I used sometimes to zoom so much.
See #881 
I used for a while

Set maxZoom to max value

---

pwnagotchi/fs/__init__.py

Fixed minor typo in fs class
"Syning" -> "Syncing".
Ran it through a spell-checker?

Fix minor typo

---

scripts/restore.sh

Signed-off-by: MikeDawg <MikeDawg@gmail.com>
Added the usage() call in the catch-all ( * ) case system of the restore script, to make its usage similar to the backup script
Wanted the scripts to all function similarly, it helps when tracking down usage/help/issues.
https://github.com/evilsocket/pwnagotchi/issues/850
Ensured that the script ran as expected, without any issues/errors.

Fixing scripts - Make all scripts usage/help similar

---

pwnagotchi/ui/faces.py

Added upload faces, which can be used when updating the application, uploading handshakes, or any other time when pwnagotchi is intentionally uploading or downloading data.
Literally just added 3 faces and descriptions.  Will look at where to appropriately call these faces in another pull request.
Will look to add faces code for update or uploading actions
Partial resolution to https://github.com/evilsocket/pwnagotchi/issues/963
(https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))
Simulated faces inside of the waveshare v2 with no issues.

Add Uploading 'Faces'

---

pwnagotchi/plugins/default/gps.py

This PR fixes a bug regarding the physical display location of the latitude and longitude as defined by the gps module.
This hasn't been tested.

Fix display bug in gps module

---

pwnagotchi/plugins/default/wpa-sec.py

Added logging.info message for plugin loading, to keep consistent with behaviour of other plugins.

Update wpa-sec.py logging

---

scripts/openbsd_connection_share.sh

Add OpenBSD share connection script
Add example to connect from OpenBSD machine.
Some people just don't use Loonix everywhere.
OpenBSD machine.

Add OpenBSD share connection script
